#!/usr/bin/env python3
"""
AI Code Detector for C Programming Language
Detects the percentage likelihood that a C code file was generated by AI.
"""

import sys
import re
import os

def read_file(file_path):
    """Read the content of the C file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

def analyze_comments(content):
    """Analyze comment density and quality."""
    lines = content.split('\n')
    total_lines = len(lines)
    comment_lines = 0
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('//') or stripped.startswith('/*') or '/*' in stripped or '*/' in stripped:
            comment_lines += 1
    comment_density = comment_lines / total_lines if total_lines > 0 else 0
    # AI-generated code often has low comment density or generic comments
    score = min(comment_density * 100, 50)  # Cap at 50% for this heuristic
    return score

def analyze_variable_naming(content):
    """Analyze variable naming patterns."""
    # Find variable declarations (simple regex for int, char, etc.)
    var_pattern = r'\b(int|char|float|double|long|short)\s+(\w+)\s*[;=]'
    variables = re.findall(var_pattern, content)
    generic_names = ['temp', 'var', 'i', 'j', 'k', 'x', 'y', 'z', 'a', 'b', 'c']
    generic_count = 0
    total_vars = len(variables)
    for _, var_name in variables:
        if var_name.lower() in generic_names or re.match(r'var\d+', var_name.lower()):
            generic_count += 1
    if total_vars > 0:
        generic_ratio = generic_count / total_vars
        score = generic_ratio * 100  # Higher generic names -> higher AI score
    else:
        score = 0
    return score

def analyze_structure(content):
    """Analyze code structure patterns."""
    score = 0
    # Check for repetitive loops
    loop_count = len(re.findall(r'\bfor\s*\(', content)) + len(re.findall(r'\bwhile\s*\(', content))
    if loop_count > 5:
        score += 20
    # Check for nested ifs
    if_count = len(re.findall(r'\bif\s*\(', content))
    if if_count > 10:
        score += 20
    # Perfect indentation (assuming 4 spaces)
    lines = content.split('\n')
    indented_lines = sum(1 for line in lines if line.startswith('    ') and line.strip())
    total_lines = len([line for line in lines if line.strip()])
    if total_lines > 0:
        indent_ratio = indented_lines / total_lines
        if indent_ratio > 0.8:
            score += 30  # AI often has consistent indentation
    return min(score, 100)

def analyze_keywords(content):
    """Analyze presence of AI-common keywords/phrases."""
    ai_phrases = [
        "include standard library",
        "main function",
        "return 0",
        "printf hello world",
        "scanf",
        "loop from 0 to n",
        "array of size",
        "pointer to",
        "struct definition"
    ]
    score = 0
    for phrase in ai_phrases:
        if phrase.lower() in content.lower():
            score += 10
    return min(score, 100)

def calculate_ai_percentage(content):
    """Calculate overall AI percentage."""
    comment_score = analyze_comments(content)
    var_score = analyze_variable_naming(content)
    struct_score = analyze_structure(content)
    keyword_score = analyze_keywords(content)
    # Weighted average: comments 20%, variables 30%, structure 30%, keywords 20%
    total_score = (comment_score * 0.2) + (var_score * 0.3) + (struct_score * 0.3) + (keyword_score * 0.2)
    return round(total_score, 2)

def main():
    if len(sys.argv) != 2:
        print("Usage: python ai_detector.py <path_to_c_file>")
        sys.exit(1)
    file_path = sys.argv[1]
    if not os.path.isfile(file_path):
        print(f"Error: '{file_path}' is not a valid file.")
        sys.exit(1)
    content = read_file(file_path)
    ai_percentage = calculate_ai_percentage(content)
    print(f"AI Detection Result for {file_path}:")
    print(f"Estimated AI-generated code percentage: {ai_percentage}%")
    if ai_percentage > 70:
        print("High likelihood of AI generation.")
    elif ai_percentage > 40:
        print("Moderate likelihood of AI generation.")
    else:
        print("Low likelihood of AI generation.")

if __name__ == "__main__":
    main()